name: Build Docker Image

on:
  push:
    branches:
      - main # Thay đổi thành branch bạn muốn build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t enteigod/your-image-name:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.enteigod }} -p ${{ secrets.pass }}

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/your-image-name:latest
