name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set DNS to Google DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:${{ github.sha }}
      - name: Push latest tag
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest
